*

diff --git a/.github/workflows/run.yaml b/.github/workflows/run.yaml
--- a/.github/workflows/run.yaml
+++ b/.github/workflows/run.yaml
@@ -13,28 +13,25 @@ jobs:
     runs-on: ubuntu-latest
 
     steps:
-    - name: Check out repository
-      uses: actions/checkout@v3
+      - name: Check out repository
+        uses: actions/checkout@v3
 
-    - name: Set up Docker
-      run: |
-        docker --version
-        sudo apt-get update
-        sudo apt-get install -y docker-compose
-        docker-compose --version
+      - name: Set up Docker
+        run: |
+          docker --version
+          sudo apt-get update
+          sudo apt-get install -y docker-compose
+          docker-compose --version
 
-    - name: Build Docker image with Cypress
-      run: |
-        docker build -t cypress-tests .
+      - name: Build Docker image with Cypress
+        run: |
+          docker build -t cypress-tests .
 
-    - name: List files in the working directory
-      run: ls -la /e2e   
+      - name: Run Cypress tests in Docker container
+        run: |
+          docker run -v ${{ github.workspace }}:/cypress/e2e/browsers:node-20.9.0-chrome-118.0.5993.88-1-ff-118.0.2-edge-118.0.2088.46-1 \
+            npx cypress run
 
-    - name: Run Cypress tests in Docker container
-      run: |
-        docker run -v ${{ github.workspace }}:/cypress/e2e/browsers:node-20.9.0-chrome-118.0.5993.88-1-ff-118.0.2-edge-118.0.2088.46-1 \
-          npx cypress run
-
-    - name: Run tests inside Docker
-      run: docker run --rm cypress-tests || echo "Tests failed, but continuing workflow."
-      continue-on-error: true
+      - name: Run tests inside Docker
+        run: docker run --rm cypress-tests || echo "Tests failed, but continuing workflow."
+        continue-on-error: true
